### ISSUE TITLE
Primary IP typo in templates

### ISSUE THREAD

**Issue by aopdal** [automateyournetwork/netbox_giftwrap#1]
For virtual machines it is used primary_ipv4 and primary_ipv6 in templates. In the API it's called primary_ip4 and primary_ip4. 
It may be more readable if result['primary_ip']['display'] is used rather than just result['primary_ip'].

I'm in the process of testing the change on markdown and html output.

**Comment by automateyournetwork** [comment]
Oh great catch thanks - if you patch it just send the code / PR !

Thanks again
